# OCI VM (servidor WG)
[Interface]
Address = 10.66.66.1/24
ListenPort = 51820
PrivateKey = kGC9krcWZJuU6LBxhZqhV5jgUgcXLxHYEBD/Wqr8vFg=
PostUp = iptables -A FORWARD -i wg0 -j ACCEPT; iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
PostDown = iptables -D FORWARD -i wg0 -j ACCEPT; iptables -t nat -D POSTROUTING -o eth0 -j MASQUERADE

# LXC vpn-oci (Proxmox Client)
[Peer]
PublicKey = nGJx7O1N44q8E/xFLM1P9uLCqgJu/Mpll3y0ckpSTjg=
AllowedIPs = 10.66.66.2/32
