apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://charts.jetstack.io
      chart: cert-manager
      targetRevision: v1.18.2
      helm:
        valueFiles:
          - $values/helm-values/cert-manager.yaml
    - repoURL: https://github.com/luizizycki/labtalos.git
      targetRevision: main
      ref: values
    - repoURL: https://github.com/luizizycki/labtalos.git
      targetRevision: main
      path: apps/cert-manager/resources
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - SkipDryRunOnMissingResource=true
