apiVersion: v1
kind: Secret
metadata:
    name: nextcloud-b2
    namespace: nextcloud
type: Opaque
stringData:
    access-key: ENC[AES256_GCM,data:1tTlhC40YPhOGGsgwkF+8gIlzQ5LaOsPCw==,iv:P1K9lVI2nItcyn2R5JSdsXMuNhoPyDuwLXsm2NGN+BU=,tag:s+/nGM2sX4XiRJgIbsve5g==,type:str]
    secret-key: ENC[AES256_GCM,data:VBB5RhY+8nJJuzSVO03qiiNUhvpFp/Ns7+PSNyU5JQ==,iv:rz/eTvTFpWmR6/VUnLXEUC7y8b1B4qs2uQ2o1YPwbyk=,tag:cjtogo3W397KPUk1WEuSrw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArTlRwb3FqeUlPZ0xFbTZH
            QXNSMmNrZ1pIUUNLSGszaHRmcU1QSEpBNUVBClFKa1B2ay8wVE50YytVMG56L3FL
            VG9iMGxrT1dqaEdzN003dmJjdStDUVkKLS0tIEhMTFVTNGh3dGFPd0NXSVNZL0RH
            OGdLQ3J3ZTlXNHQzbXpIaUJvSmxtdXMKqU/V8jqvam/1YDPQykDAv9zDkoSZng2l
            S8AedUHhMK/HLfwXKepmEAeTGFnESLFdG7VKZqj+rRcinZOGELrN6w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1amv76l3jnp0rt7cthchmh3jdasdjjuxdqt6dhqha475jfepqlfgs3h0nfq
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-22T01:41:56Z"
    mac: ENC[AES256_GCM,data:QQc8qhrPWBrD027w3pTv9H6KIgK/9EdZrCBwL/6UQTU2kB/aLjzCEJJxT/yme8Wvg+Lten2I+iZtvlAvMzPOv2Svd8cXowY6ykLl0jmx/vpPcd/AZWO0Z/8TZ3PFmIX7NNj62BqsAGkKLTDiM93ziSxi3RurV/5epFuq6cVxYf8=,iv:4ltO9E1pj0RLHfHULDMCLiZXQgfe4VeGJJB3sOWm6Oc=,tag:R1xKW3cAaunLQTgXdqEtwA==,type:str]
    version: 3.13.1
